#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0
cp -r ../mesh/constant/polyMesh constant/polyMesh
cp ../mesh/constant/cellToRegion constant/cellToRegion

# Remove surfaces and features
# rm -rf constant/triSurface
# rm -rf constant/extendedFeatureEdgeMesh

#------------------------------------------------------------------------------
