#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


#- For parallel running: set the initial fields
restore0Dir

pimpleFoam

touch open.foam

#------------------------------------------------------------------------------
